defaults :
  - modulus_default
  - arch:
      - afno
  - scheduler: cosine_annealing
  - optimizer: adam
  - loss: sum
  - _self_

arch:
  afno:
    patch_size: 8
    embed_dim: 512
    depth: 10
    num_blocks: 8

optimizer:
  lr: 0.0005

scheduler:
  T_max: 80000

custom:
  n_channels: 20
  tstep: 1
  n_tsteps: 1
  training_data_path: "/workspace/python/source_code/fourcastnet/data/train" # Training dataset path here
  test_data_path:     "/workspace/python/source_code/fourcastnet/data/test" # Test dataset path here
  num_workers:
    grid: 1
    validation: 1
  tag:

batch_size:
  grid: 1
  validation: 1

training:
  amp: true
  rec_constraint_freq: 10000
  rec_results_freq : 1000
  save_network_freq: 1000
  print_stats_freq: 100
  summary_freq: 1000
  max_steps : 71000 

